### ISSUE TITLE
Change Select Range

### ISSUE THREAD

**Issue by xuaninbox** [concurlabs/CXDurationPicker#1]
Hi,

Nice Work!! but could u explain how to use it? i just put the class in a UiView in the interface builder, but i can't seem to change the selected range.

Thanks!

**Comment by rapuckett** [comment]
Hi. I just added a demo project. Please let me know how it goes.

**Comment by xuaninbox** [comment]
Thank u so much for update the demo, i finally get it to work! its awesome, best rage selector i found so far! Thanks!
