### ISSUE TITLE
Calendar shows January 2015 instead of January 2016

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#12]
Scrolling the calendar down to where December 2015 transitions into January 2016.
The calendar shows December 2015, January 2015, February 2016.

**Comment by rapuckett** [comment]
Unable to repro (see attached). Is this phone or simulator? Does this happen upon initially scrolling down?

![screen shot 2015-05-10 at 4 34 58 pm](https://cloud.githubusercontent.com/assets/915724/7556732/c919e28e-f732-11e4-9f2c-76dc365542c0.png)

Also: As this is a public repo please don't include any company-specific info, such as internal Jira issues, etc.

**Comment by bixbarton** [comment]
Ratan was testing this on iPhone device, not simulator. Perhaps it is a problem on device only?
