### ISSUE TITLE
Check-in and Check-out dates are always in US format

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#15]
Check-in and Check-out dates are always in US format irrespective of the device regional settings. Tested when changing settings to UK and India. Expected to see dd/mm/yyyy but always shows in US format mm/dd/yyyy

**Comment by rapuckett** [comment]
What method are you using to get/create this date string?

Also: As this is a public repo please don't include any company-specific info, such as internal Jira issues, etc.

Thanks.

**Comment by bixbarton** [comment]
I'm calling setStartDateString on the CXDurationModeSwitch. This expects a string, so I pass in the result of calling CXDurationPickerUtils stringFromPickerDate with the CXDuraitonPickerView startDate.

stringFromPickerDate has its date format hardcoded to @"E, MMM d"

**Comment by rapuckett** [comment]
Now creates a standard "short format" date utilizing device's locale.
