### ISSUE TITLE
Selecting checkout date earlier than checkin should be treated as a new checkin date.

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#16]
Edge case.

If you have selected a date range, such as next week. If you select CheckOut on the switcher and then click todays date, it should recognise that the date is earlier than the current checkout date and treat this as a CheckIn selection.

**Comment by rapuckett** [comment]
This should be achievable by responding to the `CXDurationPickerViewDelegate` protocol and arranging the start/end dates as desired.
