### ISSUE TITLE
If you select a start date after the end date, it treats it as an invalid start date and does not update the switch panel dates

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#3]

**Comment by rapuckett** [comment]
Addressed in 95156635ae6bd7c990adc9cd07d7a2ac8c46789a

The issue describes something that only applies to the demo, not to the Duration Picker itself. Updated the demo to show how this can be accomplished. Also fixed a bug in the demo where the Mode Switch started out with incorrect dates.
