### ISSUE TITLE
when a start date has been selected, the switch panel should change mode to end date. I then guess that if you select an end date the panel should change mode back to start date again

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#4]

**Comment by rapuckett** [comment]
Addressed in commit be94caba496ee8dddcb1492ca8d9aa4df35dfab1

Note that the "switch panel" is not strictly part of the duration picker - it's intended to support the duration picker in the demo app (though it may make sense to create a first-class control out of it some day). In any event, added the ability to programmatically set the mode on it, via "setMode" method. Demo app now shows how to set end date upon selection of a start date.
