### ISSUE TITLE
Calendar loads 6 months ahead

### ISSUE THREAD

**Issue by acubillo** [concurlabs/CXDurationPicker#41]
I was trying to implement this library and customize it to my UI. The customization was a charm. But, when running it on my device the CXDurationPickerView component scrolls to Nov 2016 (we are currently in May 2016). I tried using the scrollToStartMonth: method but it was unsuccessful. 

The demo works fine, but it seems (comparing both the pod and the demo folder) the library code is not the same as current pod version 0.16.1

Can you fix this? 

Thanks!

**Comment by rapuckett** [comment]
Looking into this today. Thanks.

**Comment by acubillo** [comment]
Update about the issue:

Apparently this only happens when I try to display the view controller modally (are you kidding me?!). If I use the navigation controller to push the view controller the calendar picker scrolls to the correct month. 

Please make the calendar to work correctly with modal navigation?

**Comment by rapuckett** [comment]
Wasn't able to completely repro issue but came close enough to believe that the problem was identified. Please check out 0.16.3. Unless there's still a problem I'll close this issue in a few days.

**Comment by rapuckett** [comment]
Closing as per previous comment.
