### ISSUE TITLE
Calendar always defaults to range today->today+2

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#5]
The calendar has a call to initWithDefaultDuration coded inside an init method. This causes a problem, as it will always draw an initial date range of today->today+2, even though we are calling setStartDate and setEndDate to use today->today+1.

![image](https://cloud.githubusercontent.com/assets/202105/7587755/757e6670-f8b0-11e4-8adc-653c5cfdda98.png)

This becomes more of a problem when you select a future date range, say May 26 - May 28. Close the VC, then come back in. Our VC passes the date range May 26 - May 28 as the startdate-enddate. The control comes up, draws the default today->today+2, then draws the May 26 - May 28. So we end up with two date ranges appearing.

![image](https://cloud.githubusercontent.com/assets/202105/7587708/419bd68a-f8b0-11e4-8fb3-991e0e994985.png)

My preference would be to remove any call to initWithDefaultDuration, and make the method public. Either this, or we need to clear any current duration when setStartDate is called. Or, we need to make clearCurrentDuration public.

**Comment by rapuckett** [comment]
Fixed.
Can now also simply set the start date and provide a duration (in days) and the calendar will compute the end date for you.
