### ISSUE TITLE
Selection of new earlier date should be treated as new check-in date.

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#9]
From ChrisW and Joanne. 

When you select a valid date that is before the current check-in date, we want to assume you want to change your check-in date - so make the newly selected date the new check-in date and then slide the pointer over to the check out date.

**Comment by rapuckett** [comment]
This should already be achievable by listening implementing protocol and interacting with CXTabView according to whatever logic you prefer.
